default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: diario-da-humanidade_development

test:
  <<: *default
  database: diario-da-humanidade_test

production:
  <<: *default
  database: diario-da-humanidade_production
  username: diario-da-humanidade
  password: <%= ENV['DIARIO-DA-HUMANIDADE_DATABASE_PASSWORD'] %>
